const express = require('express');
const axios = require('axios');
const router = express.Router();

// ============================================
// CONFIGURATION
// ============================================
const DELHIVERY_API_URL = process.env.DELHIVERY_API_URL || 'https://track.delhivery.com';
const DELHIVERY_API_KEY = process.env.DELHIVERY_API_KEY;

// আপনার পিকআপ লোকেশন ডিটেইলস
const PICKUP_LOCATION = {
    name: 'AKASH DAS',
    address: 'BG SHOPPING COMPLEX, GROUND FLOOR, KALIPUR UDAYAN, DANKUNI, HOOGHLY',
    city: 'Dankuni',
    state: 'West Bengal',
    pincode: '712311',
    phone: '6290645345',
    email: 'adas58922@gmail.com'
};

console.log('✅ Real Shipping API Loaded');
console.log('📍 Pickup Location:', PICKUP_LOCATION.name);
console.log('📍 API URL:', DELHIVERY_API_URL);

router.post('/create-label', async (req, res) => {
    try {
        const { shipmentData } = req.body;
        const orderId = shipmentData?.shipment?.order_id || `ORD-${Date.now()}`;
        
        console.log('📦 Creating shipping label for:', orderId);

        // ✅ সঠিক Express API ফরম্যাট
        const payload = {
            format: 'json',
            data: {
                pickup_location: {
                    name: PICKUP_LOCATION.name,
                    address: PICKUP_LOCATION.address,
                    city: PICKUP_LOCATION.city,
                    state: PICKUP_LOCATION.state,
                    pincode: PICKUP_LOCATION.pincode,
                    phone: PICKUP_LOCATION.phone
                },
                shipments: [{
                    order_id: orderId,
                    name: shipmentData?.shipment?.name || 'Customer',
                    address: shipmentData?.shipment?.address || 'N/A',
                    city: shipmentData?.shipment?.city || 'Mumbai',
                    state: shipmentData?.shipment?.state || 'Maharashtra',
                    pincode: shipmentData?.shipment?.pincode || '700001',
                    phone: shipmentData?.shipment?.phone || '9876543210',
                    quantity: shipmentData?.shipment?.quantity || 1,
                    total_weight: shipmentData?.shipment?.total_weight || '0.5',
                    length: shipmentData?.shipment?.length || '10',
                    breadth: shipmentData?.shipment?.breadth || '10',
                    height: shipmentData?.shipment?.height || '10',
                    product_description: shipmentData?.shipment?.product_description || 'Jewellery',
                    invoice_number: shipmentData?.shipment?.invoice_number || orderId,
                    cod_amount: shipmentData?.shipment?.cod_amount || '0'
                }]
            }
        };

        console.log('📤 Sending to Delhivery API...');
        console.log('📤 Payload:', JSON.stringify(payload, null, 2));

        const response = await axios.post(
            `${DELHIVERY_API_URL}/api/cmu/create.json`,
            payload,  
            {
                headers: {
                    'Authorization': `Token ${DELHIVERY_API_KEY}`,
                    'Content-Type': 'application/json' 
                },
                timeout: 30000
            }
        );

        console.log('📥 Delhivery Response:', JSON.stringify(response.data, null, 2));

        if (!response.data || response.data.error === true) {
            throw new Error(response.data?.rmk || response.data?.message || 'Delhivery API returned error');
        }

        let awbNumber = null;
        let shipmentId = null;
        let labelUrl = null;

        if (response.data?.packages?.length > 0) {
            const pkg = response.data.packages[0];
            awbNumber = pkg.waybill || pkg.awb_number;
            shipmentId = pkg.shipment_id || pkg.id;
            labelUrl = pkg.label_url || null;
        }

        if (!awbNumber) {
            throw new Error('No AWB number generated by Delhivery');
        }

        console.log(`✅ AWB GENERATED: ${awbNumber}`);

        res.json({
            success: true,
            awbNumber: awbNumber,
            shipmentId: shipmentId,
            labelUrl: labelUrl,
            isLocal: false,
            message: '✅ Real AWB Generated',
            apiResponse: response.data
        });

    } catch (error) {
        console.error('❌ Create label error:', error.message);
        res.status(500).json({
            success: false,
            error: error.message,
            details: error.response?.data || null
        });
    }
});

// ============================================
// TRACK SHIPMENT - REAL ONLY
// ============================================
router.get('/track/:awbNumber', async (req, res) => {
    try {
        const { awbNumber } = req.params;

        console.log('🔍 Tracking REAL AWB:', awbNumber);

        // লোকাল AWB চেক করুন - যদি কেউ লোকাল দেয় তাহলে এরর দিন
        if (awbNumber.startsWith('AAJ')) {
            return res.status(400).json({
                success: false,
                error: 'Local AWB not supported. Please use real AWB from Delhivery.'
            });
        }

        const response = await axios.get(
            `${DELHIVERY_API_URL}/api/v1/packages/json/${awbNumber}`,
            {
                headers: {
                    'Authorization': `Token ${DELHIVERY_API_KEY}`,
                    'Content-Type': 'application/json'
                },
                timeout: 10000
            }
        );

        if (!response.data?.ShipmentData?.[0]) {
            throw new Error('Shipment not found in Delhivery system');
        }

        const shipment = response.data.ShipmentData[0];

        res.json({
            success: true,
            awbNumber: awbNumber,
            status: shipment.Status?.Status || 'In Transit',
            isLocal: false,
            details: shipment,
            trackingUrl: `https://www.delhivery.com/track/${awbNumber}`
        });

    } catch (error) {
        console.error('❌ Tracking error:', error.message);
        res.status(500).json({
            success: false,
            error: error.message,
            details: error.response?.data || null
        });
    }
});

// ============================================
// REQUEST PICKUP - REAL ONLY
// ============================================
router.post('/request-pickup', async (req, res) => {
    try {
        const { awbNumber, pickupData } = req.body;

        console.log('🚚 Requesting REAL pickup for AWB:', awbNumber);

        if (!awbNumber) {
            return res.status(400).json({
                success: false,
                error: 'AWB number is required'
            });
        }

        // লোকাল AWB চেক করুন
        if (awbNumber.startsWith('AAJ')) {
            return res.status(400).json({
                success: false,
                error: 'Local AWB not supported. Please use real AWB from Delhivery.'
            });
        }

        const payload = {
            waybill: awbNumber,
            pickup_date: pickupData?.pickup_date || new Date().toISOString().split('T')[0],
            pickup_time: pickupData?.pickup_time || '10:00-18:00',
            weight: pickupData?.weight || '0.5',
            quantity: pickupData?.quantity || 1
        };

        const response = await axios.post(
            `${DELHIVERY_API_URL}/api/v1/pickup/request`,
            payload,
            {
                headers: {
                    'Authorization': `Token ${DELHIVERY_API_KEY}`,
                    'Content-Type': 'application/json'
                },
                timeout: 30000
            }
        );

        console.log('📥 Pickup Response:', JSON.stringify(response.data, null, 2));

        if (!response.data || response.data.error === true) {
            throw new Error(response.data?.message || 'Pickup request failed');
        }

        res.json({
            success: true,
            awbNumber: awbNumber,
            pickupStatus: 'scheduled',
            isLocal: false,
            message: '✅ Pickup scheduled with Delhivery',
            pickupDetails: response.data
        });

    } catch (error) {
        console.error('❌ Request pickup error:', error.message);
        res.status(500).json({
            success: false,
            error: error.message,
            details: error.response?.data || null
        });
    }
});

// ============================================
// PRINT LABEL - REAL ONLY (ডেলিভারি থেকে লেবেল ডাউনলোড)
// ============================================
router.get('/print-label/:awbNumber', async (req, res) => {
    try {
        const { awbNumber } = req.params;

        console.log('🖨️ Printing REAL label for AWB:', awbNumber);

        // লোকাল AWB চেক করুন
        if (awbNumber.startsWith('AAJ')) {
            return res.status(400).json({
                success: false,
                error: 'Local AWB not supported. Please use real AWB from Delhivery.'
            });
        }

        // ডেলিভারি থেকে লেবেল ডাউনলোড করুন
        const response = await axios.get(
            `${DELHIVERY_API_URL}/api/v1/label/${awbNumber}`,
            {
                headers: {
                    'Authorization': `Token ${DELHIVERY_API_KEY}`
                },
                responseType: 'arraybuffer',
                timeout: 15000
            }
        );

        res.set({
            'Content-Type': 'application/pdf',
            'Content-Disposition': `attachment; filename=label-${awbNumber}.pdf`
        });

        res.send(response.data);

    } catch (error) {
        console.error('❌ Print label error:', error.message);
        res.status(500).json({
            success: false,
            error: error.message,
            details: error.response?.data || null
        });
    }
});

// ============================================
// CREATE REVERSE PICKUP - REAL ONLY
// ============================================
router.post('/reverse-pickup', async (req, res) => {
    try {
        const { pickupData } = req.body;

        console.log('🔄 Creating REAL reverse pickup...');

        if (!pickupData) {
            return res.status(400).json({
                success: false,
                error: 'Pickup data is required'
            });
        }

        const payload = {
            shipments: [{
                add: pickupData?.address || 'N/A',
                phone: pickupData?.phone || '9876543210',
                payment_mode: 'Prepaid',
                name: pickupData?.name || 'Customer',
                pin: pickupData?.pincode || '700001',
                order: `RET-${Date.now()}`,
                country: 'India',
                cod_amount: 0,
                waybill: '',
                shipping_mode: 'Surface'
            }],
            pickup_location: {
                name: PICKUP_LOCATION.name,
                city: PICKUP_LOCATION.city,
                pin: PICKUP_LOCATION.pincode,
                country: 'India',
                phone: PICKUP_LOCATION.phone,
                add: PICKUP_LOCATION.address
            }
        };

        const postData = `format=json&data=${encodeURIComponent(JSON.stringify(payload))}`;

        const response = await axios.post(
            `${DELHIVERY_API_URL}/api/cmu/create.json`,
            postData,
            {
                headers: {
                    'Authorization': `Token ${DELHIVERY_API_KEY}`,
                    'Content-Type': 'application/x-www-form-urlencoded'
                },
                timeout: 30000
            }
        );

        console.log('📥 Reverse pickup response:', JSON.stringify(response.data, null, 2));

        if (response.data?.error === true) {
            throw new Error(response.data?.rmk || 'Reverse pickup failed');
        }

        let returnAwb = null;
        if (response.data?.packages?.length > 0) {
            const pkg = response.data.packages[0];
            returnAwb = pkg.waybill || pkg.awb_number;
        }

        if (!returnAwb) {
            throw new Error('No return AWB generated');
        }

        res.json({
            success: true,
            returnAwbNumber: returnAwb,
            isLocal: false,
            message: '✅ Real Return AWB Generated'
        });

    } catch (error) {
        console.error('❌ Reverse pickup error:', error.message);
        res.status(500).json({
            success: false,
            error: error.message,
            details: error.response?.data || null
        });
    }
});

// ============================================
// HEALTH CHECK
// ============================================
router.get('/health', (req, res) => {
    res.json({
        status: 'OK',
        service: 'Real Shipping API',
        pickupLocation: PICKUP_LOCATION.name,
        pickupPincode: PICKUP_LOCATION.pincode,
        apiUrl: DELHIVERY_API_URL,
        apiKey: DELHIVERY_API_KEY ? '✅ Configured' : '❌ Missing',
        mode: 'REAL ONLY - No Local Fallback',
        timestamp: new Date().toISOString()
    });
});

module.exports = router;
